"""Verify that the submission draft and authoritative result tables agree."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path
from zipfile import ZipFile

import pandas as pd


def close(actual: float, expected: float, tolerance: float = 1e-6) -> bool:
    return abs(float(actual) - expected) <= tolerance


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def consensus_rows(root: Path) -> pd.DataFrame:
    aggregate = root / "outputs/runs/20261002_3rscan_consensus_vitg_clean_v2/summary_all.csv"
    rows = []
    if aggregate.exists():
        source_rows = pd.read_csv(aggregate)
        source_rows = source_rows[~source_rows.pair.astype(str).str.contains("target")]
        iterator = ((row.pair, row) for row in source_rows.itertuples(index=False))
    else:
        paths = sorted((root / "outputs/runs").glob("*_consensus_*_vitg_diag/summary.csv"))
        iterator = []
        for path in paths:
            match = re.search(r"_consensus_(.+)_vitg_diag$", path.parent.name)
            if match is None or match.group(1) == "target":
                continue
            iterator.append((match.group(1), pd.read_csv(path).iloc[0]))
    for pair, row in iterator:
        rows.append({
            "pair": pair,
            "queries": float(row.queries),
            "inliers": float(row.inliers),
            "coverage": float(row.inlier_coverage),
            "semantic": float(row.inlier_semantic_accuracy),
            "rotation": float(row.rotation_error_deg),
            "translation": float(row.translation_error_m),
        })
    return pd.DataFrame(rows)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path("."))
    args = parser.parse_args()
    root = args.root.resolve()

    source = consensus_rows(root)
    require(len(source) == 16, f"expected 16 source pairs, found {len(source)}")
    weighted_coverage = source.inliers.sum() / source.queries.sum()
    weighted_semantic = (source.inliers * source.semantic).sum() / source.inliers.sum()
    pose_success = ((source.rotation < 5.0) & (source.translation < 0.25)).sum()
    require(close(weighted_coverage, 0.3038277511961722), f"ViT-G source coverage drifted: {weighted_coverage}")
    require(close(weighted_semantic, 0.8499562554680665), f"ViT-G source semantics drifted: {weighted_semantic}")
    require(pose_success == 1, f"ViT-G source strict pose count drifted: {pose_success}")

    target = pd.read_csv(root / "outputs/runs/20261002_3rscan_consensus_vitg_clean_v2/summary_all.csv")
    target = target[target.pair.astype(str).str.contains("target")].iloc[0]
    require(close(target.inlier_coverage, 0.6800748362956034), "target coverage drifted")
    require(close(target.inlier_semantic_accuracy, 0.9353507565337001), "target semantic precision drifted")

    # Guard the provenance boundary that matters for the clean claim: every
    # aggregate row must have a matching query-level diagnostic generated by
    # an evaluator that did not use the hidden alignment or annotation labels
    # during candidate construction.
    diagnostic_dirs = sorted((root / "outputs/runs").glob("20261002_3rscan_consensus_*_vitg_diag_clean"))
    require(len(diagnostic_dirs) == 17, f"clean diagnostic pair count drifted: {len(diagnostic_dirs)}")
    for diagnostic_dir in diagnostic_dirs:
        status = json.loads((diagnostic_dir / "status.json").read_text(encoding="utf-8"))
        require(status.get("known_alignment_used_for_selection") is False,
                f"alignment leakage flag in {diagnostic_dir.name}")
        diagnostics = pd.read_csv(diagnostic_dir / "query_diagnostics.csv")
        require("query_evaluable" in diagnostics.columns,
                f"query-evaluable provenance missing in {diagnostic_dir.name}")
        require({
            "query_semantic_id", "selected_reference_semantic_id",
            "query_instance_id", "selected_reference_instance_id",
        }.issubset(diagnostics.columns),
                f"post-hoc label fields missing in {diagnostic_dir.name}")
        summary = pd.read_csv(diagnostic_dir / "summary.csv").iloc[0]
        require(len(diagnostics) == int(summary.matching_query_points),
                f"diagnostic/matching row mismatch in {diagnostic_dir.name}")
        require(int(diagnostics.query_evaluable.astype(bool).sum()) == int(summary.queries),
                f"diagnostic/evaluation denominator mismatch in {diagnostic_dir.name}")

    regression_dir = root / "outputs/runs/20261002_regression_target_vitg_after_controls"
    clean_target_dir = root / "outputs/runs/20261002_3rscan_consensus_target_vitg_diag_clean"
    for artifact_name in ("summary.csv", "query_diagnostics.csv"):
        require(
            (regression_dir / artifact_name).read_bytes() == (clean_target_dir / artifact_name).read_bytes(),
            f"default evaluator regression drifted in {artifact_name}",
        )

    vitl = pd.read_csv(root / "outputs/runs/20261002_3rscan_consensus_vitl_clean/summary_all.csv")
    original_pairs = set(vitl.pair)
    # The scale-control comparison is the original matched 14-pair artifact;
    # the expanded v2 aggregate is used for the 16-source robustness claim.
    vitg_original = pd.read_csv(root / "outputs/runs/20261002_3rscan_consensus_vitg_clean/summary_all.csv")
    vitg_original = vitg_original[vitg_original.pair.isin(original_pairs)]
    vitl_semantic = (vitl.inliers * vitl.inlier_semantic_accuracy).sum() / vitl.inliers.sum()
    vitg_original_semantic = (vitg_original.inliers * vitg_original.inlier_semantic_accuracy).sum() / vitg_original.inliers.sum()
    require(close(vitl_semantic, 0.8506306705023235), "clean ViT-L scale control drifted")
    require(close(vitg_original_semantic, 0.868959512407488), "clean ViT-G scale control drifted")

    fpfh = pd.read_csv(root / "outputs/runs/20261002_fpfh_17pair_clean/summary_all.csv")
    one_way = fpfh[fpfh.method == "fpfh_one_way"]
    fpfh_coverage = one_way.inliers.sum() / (one_way.inliers / one_way.inlier_coverage).sum()
    fpfh_semantic = (one_way.inliers * one_way.inlier_semantic_accuracy).sum() / one_way.inliers.sum()
    fpfh_pose = ((one_way.rotation_error_deg < 5.0) & (one_way.translation_error_m < 0.25)).sum()
    require(len(one_way) == 17, "FPFH pair count drifted")
    require(close(fpfh_coverage, 0.043063849333945727), "FPFH coverage drifted")
    require(close(fpfh_semantic, 0.6746666666666666), "FPFH semantic precision drifted")
    require(fpfh_pose == 0, "FPFH strict pose count drifted")

    fcgf = pd.read_csv(root / "outputs/runs/20261002_fcgf_17pair_clean/summary_all.csv")
    fcgf = fcgf[fcgf.top_k == 20]
    fcgf_coverage = fcgf.inliers.sum() / fcgf.query_queries.sum()
    fcgf_semantic = (fcgf.inlier_semantic_accuracy * fcgf.inliers).sum() / fcgf.inliers.sum()
    fcgf_pose = ((fcgf.rotation_error_deg < 5.0) & (fcgf.translation_error_m < 0.25)).sum()
    require(len(fcgf) == 17, "FCGF pair count drifted")
    require(close(fcgf_coverage, 0.18731773903331886), "FCGF coverage drifted")
    require(close(fcgf_semantic, 0.5332891685988738), "FCGF semantic precision drifted")
    require(fcgf_pose == 0, "FCGF strict pose count drifted")

    # Downstream control closure: the geometry baselines now save the selected
    # labels used for the label-transfer comparison, rather than only an
    # aggregate inlier accuracy.  Lock the aggregate rows and provenance so
    # the new task-level comparison cannot silently change denominator or leak
    # the hidden alignment into selection.
    baseline_transfer = pd.read_csv(
        root / "outputs/runs/20261012_baseline_label_transfer/baseline_transfer_table.csv"
    )
    require(len(baseline_transfer) == 6, "baseline label-transfer row count drifted")
    expected_transfer = {
        ("source", "ViT-G consensus"): (0.3038277511961722, 0.415, 0.390, 0.850),
        ("source", "FPFH one-way"): (0.03773584905660377, 0.34772412491841187, 0.31125356261086273, 0.6258064516129033),
        ("source", "FCGF top-20"): (0.18819776714513556, 0.1445838736092003, 0.14764155082664449, 0.5116525423728814),
        ("target", "ViT-G consensus"): (0.6800748362956034, 0.855, 0.723, 0.935),
        ("target", "FPFH one-way"): (0.13184584178498987, 0.8277938415509573, 0.8277938415509573, 0.9076923076923077),
        ("target", "FCGF top-20"): (0.17492984097287184, 0.6418296309425341, 0.6418296309425341, 0.8609625668449198),
    }
    for row in baseline_transfer.itertuples(index=False):
        key = (row.dataset, row.method)
        require(key in expected_transfer, f"unexpected baseline transfer row: {key}")
        expected = expected_transfer[key]
        require(close(row.coverage, expected[0]), f"baseline transfer coverage drifted: {key}")
        require(close(row.semantic_mIoU, expected[1]), f"baseline transfer semantic mIoU drifted: {key}")
        require(close(row.instance_mIoU, expected[2]), f"baseline transfer instance mIoU drifted: {key}")
        require(close(row.semantic_accuracy, expected[3]), f"baseline transfer semantic accuracy drifted: {key}")
    for directory, diagnostic_name in (
        ("20261012_fpfh_17pair_diag", "query_diagnostics_fpfh_one_way.csv"),
        ("20261012_fcgf_17pair_diag", "query_diagnostics_k20.csv"),
    ):
        diagnostic_dirs = sorted((root / "outputs/runs" / directory).glob("*"))
        require(len(diagnostic_dirs) == 17, f"{directory} pair count drifted")
        for diagnostic_dir in diagnostic_dirs:
            status = json.loads((diagnostic_dir / "status.json").read_text(encoding="utf-8"))
            require(status.get("known_alignment_used_for_selection") is False,
                    f"baseline alignment leakage flag in {diagnostic_dir.name}")
            diagnostic = pd.read_csv(diagnostic_dir / diagnostic_name)
            require({
                "query_semantic_id", "selected_reference_semantic_id",
                "query_instance_id", "selected_reference_instance_id",
                "query_evaluable", "consensus_inlier",
            }.issubset(diagnostic.columns), f"baseline labels missing in {diagnostic_dir.name}")
            require(len(diagnostic) > 0, f"empty baseline diagnostics in {diagnostic_dir.name}")

    negative = pd.read_csv(root / "outputs/runs/20261002_negative_control_vitg/summary_all.csv")
    negative_source = negative[negative.pair != "target"]
    negative_target = negative[negative.pair == "target"].iloc[0]
    negative_coverage = negative_source.inliers.sum() / negative_source.queries.sum()
    negative_semantic = (
        negative_source.inliers * negative_source.inlier_semantic_accuracy
    ).sum() / negative_source.inliers.sum()
    negative_pose = ((negative_source.rotation_error_deg < 5.0) & (negative_source.translation_error_m < 0.25)).sum()
    require(len(negative) == 17, "descriptor-permutation pair count drifted")
    require(close(negative_coverage, 0.1049973418394471), "negative-control coverage drifted")
    require(close(negative_semantic, 0.46329113924050636), "negative-control semantic precision drifted")
    require(int(negative_pose) == 0, "negative-control strict pose count drifted")
    require(close(negative_target.inlier_coverage, 0.07857811038353602), "negative-control target coverage drifted")
    require(close(negative_target.inlier_semantic_accuracy, 0.03571428571428571), "negative-control target semantics drifted")
    require(close(negative_target.rotation_error_deg, 162.23300257403707), "negative-control target pose drifted")
    negative_names = [
        "0cac", "20c993", "4aca", "5630", "6bde", "751a", "95be", "c670",
        "chairs", "pair02", "pair03", "pair04", "pair05", "pair06", "pair07", "pair08",
    ]
    negative_dirs = [root / "outputs/runs" / f"20261002_negative_control_{name}_vitg" for name in negative_names]
    negative_dirs.append(root / "outputs/runs/20261002_negative_control_target_vitg_v2")
    for negative_dir in negative_dirs:
        status = json.loads((negative_dir / "status.json").read_text(encoding="utf-8"))
        require(status.get("descriptor_control") == "permuted_reference",
                f"negative-control provenance missing in {negative_dir.name}")

    calibration = pd.read_csv(root / "outputs/runs/20261002_selective_calibration_vitg_clean_v2/leave_one_pair_out.csv")
    fit = calibration[
        (calibration.precision_target == 0.9)
        & (calibration.held_pair == "target_source_only_fit")
        & (calibration.score == "low_spatial_residual")
    ].iloc[0]
    require(close(-fit.threshold, 0.0409313847206034), "calibration threshold drifted")
    require(close(fit.target_coverage, 0.2207670720299345), "target calibrated coverage drifted")
    require(close(fit.target_semantic_precision, 0.9661016949152542), "target calibrated precision drifted")

    cross_fitted = pd.read_csv(
        root / "outputs/runs/20261002_selective_calibration_vitg_clean_v2/cross_fitted_summary.csv"
    )
    cross_fitted_90 = cross_fitted[
        (cross_fitted.precision_target == 0.9)
        & (cross_fitted.score == "low_spatial_residual")
    ].iloc[0]
    require(cross_fitted_90.status == "complete", "cross-fitted calibration is incomplete")
    require(int(cross_fitted_90.selected_queries) == 1364, "cross-fitted selected query count drifted")
    require(close(cross_fitted_90.coverage, 1364 / 15048), "cross-fitted coverage drifted")
    require(close(cross_fitted_90.weighted_semantic_precision, 0.7661290322580645),
            "cross-fitted semantic precision drifted")
    require(int(cross_fitted_90.pairs_below_precision_target) == 6,
            "cross-fitted below-target pair count drifted")

    risk_controlled = pd.read_csv(root / "outputs/runs/20261002_risk_controlled_calibration_vitg_clean/summary.csv")
    risk_source = risk_controlled[risk_controlled.dataset == "source"].iloc[0]
    risk_target = risk_controlled[risk_controlled.dataset == "target"].iloc[0]
    require(close(risk_source.threshold, 0.0330402718601783), "risk-controlled threshold drifted")
    require(close(risk_source.semantic_lower_bound, 0.9006895187327857), "risk lower bound drifted")
    require(close(risk_source.coverage, 0.061004784688995214), "risk source coverage drifted")
    require(close(risk_target.coverage, 0.1412535079513564), "risk target coverage drifted")
    require(close(risk_target.semantic_precision, 0.9867549668874173), "risk target precision drifted")
    risk_status = json.loads(
        (root / "outputs/runs/20261002_risk_controlled_calibration_vitg_clean/status.json").read_text(encoding="utf-8")
    )
    require(risk_status.get("target_evaluation_is_post_hoc") is True, "risk target provenance drifted")

    risk_audit = pd.read_csv(
        root / "outputs/runs/20261004_risk_control_selection_audit_vitg_clean/summary.csv"
    )
    fixed_source = risk_audit[
        (risk_audit.dataset == "source") & (risk_audit.operating_point == "fixed_2cm_audit")
    ].iloc[0]
    fixed_target = risk_audit[
        (risk_audit.dataset == "target") & (risk_audit.operating_point == "fixed_2cm_audit")
    ].iloc[0]
    require(close(fixed_source.coverage, 0.019271664008506113), "fixed risk-audit source coverage drifted")
    require(close(fixed_source.semantic_precision, 0.9379310344827586), "fixed risk-audit source precision drifted")
    require(close(fixed_source.semantic_lower_bound, 0.9093450487377718), "fixed risk-audit lower bound drifted")
    require(close(fixed_target.coverage, 0.03274087932647334), "fixed risk-audit target coverage drifted")
    require(close(fixed_target.semantic_precision, 1.0), "fixed risk-audit target precision drifted")
    risk_audit_status = json.loads(
        (root / "outputs/runs/20261004_risk_control_selection_audit_vitg_clean/status.json").read_text(encoding="utf-8")
    )
    require(risk_audit_status["candidate_prefixes"] == 14949, "risk-audit prefix count drifted")
    require(risk_audit_status["familywise_feasible"] is False, "risk-audit correction unexpectedly feasible")
    require(risk_audit_status["fixed_threshold_is_retrospective_audit"] is True,
            "risk-audit fixed-threshold provenance drifted")
    require(close(risk_audit_status["max_adjusted_lower_bound"], 0.8744986872885274),
            "risk-audit adjusted bound drifted")

    k_sweep = pd.read_csv(root / "outputs/runs/20261003_k_sweep_vitg_clean/summary.csv")
    k_source = k_sweep[k_sweep.split == "source"]
    k_target = k_sweep[k_sweep.split == "target"]
    require(set(k_source.top_k) == {1, 5, 10, 20, 50}, "K-sweep source grid drifted")
    require(set(k_target.top_k) == {1, 5, 10, 20, 50}, "K-sweep target grid drifted")
    k20_source = k_source[k_source.top_k == 20].iloc[0]
    k20_target = k_target[k_target.top_k == 20].iloc[0]
    require(close(k20_source.weighted_coverage, 0.3038277511961722), "K-sweep K=20 source coverage drifted")
    require(close(k20_source.weighted_semantic_precision, 0.8499562554680665), "K-sweep K=20 source precision drifted")
    require(close(k20_target.weighted_coverage, 0.6800748362956034), "K-sweep K=20 target coverage drifted")
    require(close(k20_target.weighted_semantic_precision, 0.9353507565337001), "K-sweep K=20 target precision drifted")
    k_status = json.loads(
        (root / "outputs/runs/20261003_k_sweep_vitg_clean/status.json").read_text(encoding="utf-8")
    )
    require(k_status["protocol"]["known_alignment_used_for_selection"] is False, "K-sweep provenance drifted")

    candidate_audit = pd.read_csv(
        root / "outputs/runs/20261005_candidate_set_audit_vitg_clean/summary.csv"
    )
    candidate_source = candidate_audit[candidate_audit.split == "source"].iloc[0]
    candidate_target = candidate_audit[candidate_audit.split == "target"].iloc[0]
    require(close(candidate_source.candidate_semantic_recall, 0.7968500794125465),
            "candidate-set source recall drifted")
    require(close(candidate_source.semantic_coverage, 0.2582402983788547),
            "candidate-set source correct coverage drifted")
    require(close(candidate_source.semantic_recovery_given_candidate, 0.3240763899583029),
            "candidate-set source recovery drifted")
    require(close(candidate_target.candidate_semantic_recall, 0.9663236669784846),
            "candidate-set target recall drifted")
    require(close(candidate_target.semantic_coverage, 0.6361085126286342),
            "candidate-set target correct coverage drifted")
    candidate_pairs = pd.read_csv(
        root / "outputs/runs/20261005_candidate_set_audit_vitg_clean/per_pair.csv"
    ).set_index("pair")
    require(close(candidate_pairs.loc["4aca"].candidate_semantic_recall, 0.195),
            "4aca candidate recall drifted")
    require(close(candidate_pairs.loc["95be"].candidate_semantic_recall, 0.692156862745098),
            "95be candidate recall drifted")
    require(int(candidate_pairs.loc["4aca"].semantic_miss_inliers) == 208,
            "4aca candidate miss-inlier count drifted")
    candidate_status = json.loads(
        (root / "outputs/runs/20261005_candidate_set_audit_vitg_clean/status.json").read_text(encoding="utf-8")
    )
    require(candidate_status["protocol"]["candidate_set_fields_are_posthoc"] is True,
            "candidate-set audit provenance drifted")
    candidate_run_dirs = sorted((root / "outputs/runs").glob("20261005_candidate_audit_*_vitg_clean"))
    require(len(candidate_run_dirs) == 17, f"candidate-audit pair count drifted: {len(candidate_run_dirs)}")
    for candidate_dir in candidate_run_dirs:
        pair = candidate_dir.name.removeprefix("20261005_candidate_audit_").removesuffix("_vitg_clean")
        clean_dir = root / "outputs/runs" / f"20261002_3rscan_consensus_{pair}_vitg_diag_clean"
        candidate_summary = (candidate_dir / "summary.csv").read_bytes()
        clean_summary = (clean_dir / "summary.csv").read_bytes()
        require(candidate_summary == clean_summary,
                f"candidate-audit summary changed clean metric for {pair}")
        audit_run_status = json.loads((candidate_dir / "status.json").read_text(encoding="utf-8"))
        require(audit_run_status.get("candidate_set_audit_posthoc") is True,
                f"candidate-audit post-hoc provenance missing for {pair}")

    scale_audit = pd.read_csv(root / "outputs/runs/20261006_backbone_scaleup_audit/summary.csv")
    scale_14 = scale_audit[scale_audit.split == "matched_14_including_target"].iloc[0]
    scale_13 = scale_audit[scale_audit.split == "matched_13_source_only"].iloc[0]
    require(int(scale_14.pairs) == 14 and int(scale_13.pairs) == 13,
            "paired scale-audit split sizes drifted")
    require(close(scale_14.semantic_delta, 0.018328841905164484),
            "paired scale-audit 14-pair delta drifted")
    require(close(scale_14.semantic_delta_ci95_lower, -0.004152180730761348),
            "paired scale-audit 14-pair lower CI drifted")
    require(close(scale_14.semantic_delta_ci95_upper, 0.05252910625310969),
            "paired scale-audit 14-pair upper CI drifted")
    require(close(scale_13.semantic_delta, 0.019177340530255993),
            "paired scale-audit source-only delta drifted")
    scale_status = json.loads(
        (root / "outputs/runs/20261006_backbone_scaleup_audit/status.json").read_text(encoding="utf-8")
    )
    require(scale_status["protocol"]["bootstrap_unit"] == "pair",
            "paired scale-audit provenance drifted")

    seed_sweep = pd.read_csv(root / "outputs/runs/20261007_seed_sweep_vitg_clean/summary.csv")
    seed_source = seed_sweep[seed_sweep.split == "source"]
    seed_target = seed_sweep[seed_sweep.split == "target"]
    require(set(seed_source.ransac_seed) == {17, 29, 41}, "seed-sweep source grid drifted")
    require(set(seed_target.ransac_seed) == {17, 29, 41}, "seed-sweep target grid drifted")
    seed_source_29 = seed_source[seed_source.ransac_seed == 29].iloc[0]
    seed_source_41 = seed_source[seed_source.ransac_seed == 41].iloc[0]
    seed_target_29 = seed_target[seed_target.ransac_seed == 29].iloc[0]
    seed_target_41 = seed_target[seed_target.ransac_seed == 41].iloc[0]
    require(close(seed_source_29.weighted_coverage, 0.3076820839978734),
            "seed-29 source coverage drifted")
    require(close(seed_source_29.weighted_semantic_precision, 0.8803455723542116),
            "seed-29 source precision drifted")
    require(close(seed_source_41.weighted_semantic_precision, 0.8312486284836516),
            "seed-41 source precision drifted")
    require(close(seed_target_29.weighted_semantic_precision, 0.9314128943758574),
            "seed-29 target precision drifted")
    require(close(seed_target_41.weighted_semantic_precision, 0.9308437067773168),
            "seed-41 target precision drifted")
    seed_stability = pd.read_csv(root / "outputs/runs/20261007_seed_sweep_vitg_clean/pair_stability.csv")
    require(close(seed_stability[seed_stability.pair == "95be"].iloc[0].semantic_range,
                  0.6896929824561404), "95be seed range drifted")
    require(close(seed_stability[seed_stability.pair == "pair06"].iloc[0].semantic_range,
                  0.6730940033807982), "pair06 seed range drifted")
    seed_status = json.loads(
        (root / "outputs/runs/20261007_seed_sweep_vitg_clean/status.json").read_text(encoding="utf-8")
    )
    require(seed_status["protocol"]["seed_sweep_is_posthoc"] is True,
            "seed-sweep provenance drifted")

    loo = calibration[
        (calibration.precision_target == 0.9)
        & (calibration.score == "low_spatial_residual")
        & (calibration.held_pair != "target_source_only_fit")
    ]
    require(len(loo) == 16, "LOO calibration fold count drifted")
    require(close(loo.held_semantic_precision.median(), 0.9101010101010102), "LOO median precision drifted")
    require(int((loo.held_semantic_precision < 0.9).sum()) == 6, "LOO below-90 count drifted")
    require(int((loo.held_semantic_precision < 0.5).sum()) == 3, "LOO below-50 count drifted")

    transfer = pd.read_csv(root / "outputs/runs/20261002_semantic_label_transfer_vitg_clean_calibrated_v2/summary.csv")
    target_transfer = transfer[
        (transfer.dataset == "target") & (transfer.selector == "source_calibrated_residual")
    ].iloc[0]
    require(close(target_transfer.semantic_mIoU, 0.8951512129407698), "target semantic mIoU drifted")
    require(close(target_transfer.instance_mIoU, 0.9071209476868098), "target instance mIoU drifted")

    framelevel_selection = json.loads(
        (root / "outputs/runs/20261002_framelevel_selection_clean/summary.json").read_text(encoding="utf-8")
    )
    require(framelevel_selection["source_best_feature"] == "layers_2_20_40", "frame-level source feature drifted")
    require(framelevel_selection["source_best_method"] == "mutual_margin_0.02", "frame-level source filter drifted")
    require(close(framelevel_selection["source_best_semantic_accuracy"], 0.6861802000331416), "frame-level source semantics drifted")
    require(close(framelevel_selection["target_semantic_accuracy"], 0.875968992248062), "frame-level target semantics drifted")
    require(close(framelevel_selection["target_coverage"], 0.1206735266604303), "frame-level target coverage drifted")
    framelevel_loso = pd.read_csv(root / "outputs/runs/20261002_framelevel_selection_clean/loso.csv")
    require(len(framelevel_loso) == 16, "frame-level LOSO fold count drifted")
    require(int((framelevel_loso.selected_method == "mutual_margin_0.02").sum()) == 13, "frame-level LOSO selection drifted")

    paper = (root / "paper/main.tex").read_text(encoding="utf-8")
    supplement = (root / "paper/supplementary.tex").read_text(encoding="utf-8")
    dossier = (root / "outputs/reports/20260922_submission_dossier.md").read_text(encoding="utf-8")
    paper_readme = (root / "paper/README.md").read_text(encoding="utf-8")
    paper_makefile = (root / "paper/Makefile").read_text(encoding="utf-8")
    require("/home/zihali" not in paper and "/home/zihali" not in supplement,
            "submission source leaks a workstation absolute path")
    require("/home/zihali" not in paper_readme,
            "paper README leaks a workstation absolute path")
    require("evaluate_3rscan_spatial_consensus.py" in paper_readme
            and "--save-query-diagnostics" in paper_readme,
            "paper README omits the clean ViT-G reproduction command")
    require("external inputs are the FCGF checkpoint" in paper_readme
            and "3RScan annotation/data root" in paper_readme,
            "paper README external-dependency boundary is underspecified")
    require("all: main supp" in paper_makefile and "main:" in paper_makefile,
            "paper default build does not include both main and supplement")
    require("\\graphicspath{{figures/}}" in paper,
            "main paper does not use the local anonymous figure bundle")
    main_pdf_bytes = (root / "paper/main.pdf").read_bytes()
    supplement_pdf_bytes = (root / "paper/supplementary.pdf").read_bytes()
    for pdf_bytes, name in ((main_pdf_bytes, "main PDF"), (supplement_pdf_bytes, "supplement PDF")):
        require(b"/home/" not in pdf_bytes and b"/tmp/" not in pdf_bytes,
                f"{name} leaks a local absolute path")
        require(b"/URI" not in pdf_bytes and b"http://" not in pdf_bytes and b"https://" not in pdf_bytes,
                f"{name} contains an external PDF URI")
    require(b"../outputs/" not in main_pdf_bytes,
            "main PDF leaks the pre-bundled figure path")
    manifest = json.loads(
        (root / "outputs/reports/20261008_submission_manifest.json").read_text(encoding="utf-8")
    )
    require(manifest.get("status") == "complete", "submission manifest is incomplete")
    require(manifest.get("absolute_paths_used") is False, "submission manifest uses absolute paths")
    require(len(manifest.get("files", [])) >= 20, "submission manifest is unexpectedly small")
    manifest_paths = {entry["path"] for entry in manifest["files"]}
    required_manifest_paths = {
        "paper/main.pdf",
        "paper/supplementary.pdf",
        "paper/figures/failure_taxonomy.pdf",
        "paper/figures/method_pipeline.pdf",
        "paper/figures/selective_correspondence_overview.pdf",
        "paper/generated_pair_table.tex",
        "paper/generated_seed_sweep_table.tex",
        "scripts/build_submission_bundle.py",
        "outputs/reports/20260922_submission_dossier.md",
        "outputs/reports/20261003_k_sensitivity.md",
        "outputs/reports/20261002_3rscan_scope_audit.md",
        "outputs/reports/20261015_cross_fitted_calibration.md",
        "outputs/runs/20261002_selective_calibration_vitg_clean_v2/cross_fitted_summary.csv",
        "outputs/reports/20261009_1776_external_validation.md",
        "outputs/reports/20261009_1776_geometry_audit.json",
        "outputs/reports/20261009_1776_annotation_projection_audit.csv",
        "outputs/reports/20261009_1776_annotation_projection_audit.json",
        "outputs/reports/20261010_4aca_external_validation.md",
        "outputs/reports/20261010_4aca_geometry_audit.json",
        "outputs/reports/20261010_4aca_annotation_projection_audit.csv",
        "outputs/reports/20261010_4aca_annotation_projection_audit.json",
        "outputs/runs/20261009_3rscan_extra_1776_pair20_s1/config.json",
        "outputs/runs/20261009_3rscan_extra_1776_pair20_s1/manifest.json",
        "outputs/runs/20261009_3rscan_extra_1776_pair20_s1/status.json",
        "outputs/runs/20261010_3rscan_extra_4aca_pair20_s1/config.json",
        "outputs/runs/20261010_3rscan_extra_4aca_pair20_s1/manifest.json",
        "outputs/runs/20261010_3rscan_extra_4aca_pair20_s1/status.json",
        "outputs/runs/20261002_runtime_target_vitg_clean/summary.csv",
        "outputs/runs/20261002_runtime_target_vitg_clean/status.json",
        "outputs/reports/20261002_selective_correspondence_vitg_clean_v2/selective_correspondence_overview.pdf",
        "outputs/reports/20261002_submission_figures_clean_v2/method_pipeline.pdf",
        "outputs/reports/20261002_submission_figures_clean_v2/failure_taxonomy.pdf",
    }
    require(required_manifest_paths <= manifest_paths,
            "submission manifest omits a required paper build artifact")
    for entry in manifest["files"]:
        relative = Path(entry["path"])
        require(not relative.is_absolute(), "submission manifest contains an absolute path")
        path = root / relative
        require(path.is_file(), f"submission manifest file missing: {relative}")
        require(path.stat().st_size == entry["bytes"], f"submission manifest size drifted: {relative}")
        require(file_sha256(path) == entry["sha256"], f"submission manifest hash drifted: {relative}")
    bundle_path = root / "outputs/reports/20261008_submission_bundle.zip"
    require(bundle_path.is_file(), "submission bundle is missing")
    expected_bundle_paths = manifest_paths | {"outputs/reports/20261008_submission_manifest.json"}
    manifest_bytes = (root / "outputs/reports/20261008_submission_manifest.json").read_bytes()
    with ZipFile(bundle_path) as bundle:
        names = bundle.namelist()
        require(len(names) == len(set(names)), "submission bundle contains duplicate paths")
        require(set(names) == expected_bundle_paths, "submission bundle contents differ from manifest")
        require(bundle.read("outputs/reports/20261008_submission_manifest.json") == manifest_bytes,
                "submission bundle manifest differs from the current manifest")
        for entry in manifest["files"]:
            relative = entry["path"]
            payload = bundle.read(relative)
            require(len(payload) == entry["bytes"], f"submission bundle size drifted: {relative}")
            require(hashlib.sha256(payload).hexdigest() == entry["sha256"],
                    f"submission bundle hash drifted: {relative}")
    pdf_submission_path = root / "outputs/reports/20261008_anonymous_submission_pdfs.zip"
    require(pdf_submission_path.is_file(), "anonymous PDF submission bundle is missing")
    with ZipFile(pdf_submission_path) as pdf_submission:
        require(set(pdf_submission.namelist()) == {"main.pdf", "supplementary.pdf"},
                "anonymous PDF submission bundle contains unexpected files")
        require(pdf_submission.read("main.pdf") == main_pdf_bytes,
                "anonymous submission main PDF differs from paper/main.pdf")
        require(pdf_submission.read("supplementary.pdf") == supplement_pdf_bytes,
                "anonymous submission supplement differs from paper/supplementary.pdf")
    for text, name in ((paper, "paper"), (dossier, "dossier")):
        if name == "paper":
            require("selective_correspondence_overview.pdf" in text,
                    "paper does not reference the bundled risk-curve figure")
        else:
            require("20261002_selective_correspondence_vitg_clean_v2" in text,
                    f"{name} uses stale risk-curve path")
        require("0.040931" in text, f"{name} uses stale calibration threshold")
        require("89.5" in text and "90.7" in text, f"{name} misses final transfer values")
        require("69.5" in text and "93.5" in text and "41.0" in text, f"{name} uses stale bootstrap intervals")
        require("20260922_selective_correspondence_full14" not in text, f"{name} references stale full14 figure")
    require("\\cite{dinov2}" in paper and "\\cite{3rscan}" in paper, "paper citation anchors missing")
    require("\\cite{fcgf}" in paper and "\\bibitem{fcgf}" in paper, "FCGF citation missing")
    for citation in ("3dmatch", "pointdsc", "geotransformer", "regtr",
                     "dust3r", "mast3r", "vggt", "semreg", "mlsemreg"):
        require(f"\\cite{{{citation}}}" in paper and f"\\bibitem{{{citation}}}" in paper, f"related-work citation missing: {citation}")
    require("FCGF top-20" in paper and "18.7\\%" in paper, "paper FCGF result missing")
    require("Downstream geometry-control comparison" in supplement
            and "generated_baseline_transfer_table.tex" in supplement
            and "82.8\\%" in supplement and "64.2\\%" in supplement
            and "not an equal-density" in supplement,
            "supplementary downstream baseline comparison missing")
    require("all thresholds and selective choices are fit source-only" in paper,
            "paper source-only decision boundary is underspecified")
    require("Permuted DINO reference" in paper and "generated_negative_control_table.tex" in supplement,
            "descriptor-permutation negative control missing")
    require("0.03304" in paper and "generated_risk_controlled_table.tex" in supplement,
            "risk-controlled calibration missing")
    require("present snapshot does not claim" in paper,
            "dated external-validation boundary missing from main paper")
    require("1,364/15,048" in paper
            and "76.6\\% retained" in paper
            and "76.6\\% retained" in supplement
            and "pooling 115 queries" in supplement
            and "85.2\\% accuracy" in supplement,
            "cross-fitted calibration audit missing")
    require("frame-level reciprocal/margin control" in paper
            and "87.6\\%" in paper and "12.1\\% target coverage" in paper,
            "frame-level confidence control missing from main paper")
    require("family-wise guarantee" in paper and "unadjusted 90.9\\%" in paper,
            "risk-control selection caveat missing")
    require("14,949 residual prefixes" in supplement and "Neither is a family-wise guarantee" in supplement,
            "risk-control selection audit missing")
    require("Top-K sensitivity" in supplement and "generated_k_sweep_table.tex" in supplement,
            "K-sensitivity audit missing")
    require("ViT-G target, $K=1$" in paper and "27.9\\%" in paper
            and "68.0\\%" in paper,
            "main paper omits the top-K coverage ablation")
    require("Post-freeze external validation" not in supplement
            and "20261013_mast3r_feasibility_audit.md" not in supplement,
            "future-dated external validation leaked into supplement")
    require("89.3\\%" in supplement and "89.4\\%" not in supplement,
            "K=10 sensitivity value drifted")
    require("19.5\\%" in paper and "69.2\\%" in paper,
            "paper candidate-set availability audit missing")
    require("[-0.4,+5.3]" in paper,
            "paper paired scale uncertainty missing")
    require("Candidate-set availability audit" in supplement
            and "generated_candidate_set_audit_table.tex" in supplement,
            "supplementary candidate-set availability audit missing")
    require("+1.8 percentage-point weighted semantic difference" in supplement,
            "supplementary paired scale uncertainty missing")
    require("RANSAC seed sensitivity" in supplement and "generated_seed_sweep_table.tex" in supplement,
            "supplementary seed-sensitivity audit missing")
    require("Protocol comparability" in supplement
            and "We do not report them as" in supplement,
            "supplementary baseline comparability boundary missing")
    require("No MASt3R smoke\nresult" in supplement
            and "frame-bank or semantic-transfer" in supplement,
            "MASt3R feasibility boundary missing")
    require("Artifact boundary" in supplement
            and "Raw 3RScan frame archives" in supplement,
            "supplementary artifact boundary missing")
    require("83.1\\% to 88.0\\%" in paper,
            "paper seed-sensitivity caveat missing")
    require("19.5%" in dossier and "69.2%" in dossier,
            "dossier candidate-set availability audit missing")
    require("generated_framelevel_table.tex" in supplement, "supplementary layer table missing")
    require("87.6% semantic" in dossier and "13/16" in dossier, "dossier frame-level source-only result missing")

    projection_audit = json.loads(
        (root / "outputs/reports/20261001_annotation_projection_audit.json").read_text(encoding="utf-8")
    )
    require(projection_audit["samples"] == 32835, "annotation audit sample count drifted")
    require(close(projection_audit["nonzero_label_rate"], 0.9984772346581392), "annotation label rate drifted")
    require(close(projection_audit["median_nearest_mesh_distance_m"], 0.0274326524458788), "annotation median distance drifted")
    require(close(projection_audit["fraction_distance_gt_0.30m"], 0.003075985990558855), "annotation tail rate drifted")

    external_audit = json.loads(
        (root / "outputs/reports/20261010_4aca_annotation_projection_audit.json").read_text(encoding="utf-8")
    )
    require(external_audit["samples"] == 1684, "second external annotation sample count drifted")
    require(close(external_audit["nonzero_label_rate"], 1.0), "second external annotation label rate drifted")
    require(close(external_audit["median_nearest_mesh_distance_m"], 0.031140818173452794),
            "second external annotation median distance drifted")
    external_k20 = pd.read_csv(
        root / "outputs/runs/20261010_3rscan_extra_4aca_vitg20_clean/summary.csv"
    ).iloc[0]
    require(close(external_k20.inlier_coverage, 0.15384615384615385), "second external coverage drifted")
    require(close(external_k20.inlier_semantic_accuracy, 0.0), "second external semantic result drifted")
    require(close(external_k20.rotation_error_deg, 117.11593110608815), "second external rotation drifted")
    external_diag = pd.read_csv(
        root / "outputs/runs/20261010_3rscan_extra_4aca_vitg20_clean/query_diagnostics.csv"
    )
    external_eval = external_diag[external_diag.query_evaluable.astype(bool)]
    require(int(external_eval.candidate_semantic_hit.astype(bool).sum()) == 166,
            "second external candidate-hit count drifted")
    require(int((external_eval.consensus_inlier.astype(bool) & external_eval.semantic_correct.astype(bool)).sum()) == 0,
            "second external correct-inlier count drifted")
    external_calibration = pd.read_csv(
        root / "outputs/runs/20261011_external_calibration_4aca_source16/leave_one_pair_out.csv"
    )
    cal_row = external_calibration[
        (external_calibration.held_pair == "target_source_only_fit")
        & (external_calibration.precision_target == 0.90)
        & (external_calibration.score == "low_spatial_residual")
    ].iloc[0]
    require(int(cal_row.target_queries) == 12, "second external calibrated query count drifted")
    require(close(cal_row.target_coverage, 12 / 689), "second external calibrated coverage drifted")
    require(close(cal_row.target_semantic_precision, 0.0), "second external calibrated semantics drifted")
    external_risk = pd.read_csv(
        root / "outputs/runs/20261011_risk_calibration_4aca_source16/summary.csv"
    )
    risk_target = external_risk[external_risk.dataset == "target"].iloc[0]
    require(int(risk_target.queries) == 7, "second external risk-controlled query count drifted")
    require(close(risk_target.coverage, 7 / 689), "second external risk-controlled coverage drifted")
    require(close(risk_target.semantic_precision, 0.0), "second external risk-controlled semantics drifted")

    external1776_calibration = pd.read_csv(
        root / "outputs/runs/20261014_external_calibration_1776_source16/leave_one_pair_out.csv"
    )
    external1776_cal = external1776_calibration[
        (external1776_calibration.held_pair == "target_source_only_fit")
        & (external1776_calibration.precision_target == 0.90)
        & (external1776_calibration.score == "low_spatial_residual")
    ].iloc[0]
    require(int(external1776_cal.target_queries) == 158, "first external calibrated query count drifted")
    require(close(external1776_cal.target_coverage, 158 / 1027), "first external calibrated coverage drifted")
    require(close(external1776_cal.target_semantic_precision, 152 / 158), "first external calibrated semantics drifted")
    external1776_risk = pd.read_csv(
        root / "outputs/runs/20261014_risk_calibration_1776_source16/summary.csv"
    )
    external1776_risk_target = external1776_risk[external1776_risk.dataset == "target"].iloc[0]
    require(int(external1776_risk_target.queries) == 105, "first external risk-controlled query count drifted")
    require(close(external1776_risk_target.coverage, 105 / 1027), "first external risk-controlled coverage drifted")
    require(close(external1776_risk_target.semantic_precision, 100 / 105), "first external risk-controlled semantics drifted")
    require(close(external1776_risk_target.semantic_mIoU, 0.8321794871794872),
            "first external risk-controlled semantic mIoU drifted")

    expected_native_runs = {
        "20260917_3rscan_pair02_s1", "20260917_3rscan_pair03_s1",
        "20260917_3rscan_pair04_s1", "20260917_3rscan_pair05_s1",
        "20260917_3rscan_target_pair_s1", "20260921_3rscan_train_0cac",
        "20260921_3rscan_train_20c993", "20260921_3rscan_train_4aca_extra",
        "20260921_3rscan_train_6bde", "20260921_3rscan_train_95be",
        "20260922_3rscan_semantic_5630", "20260922_3rscan_semantic_751a",
        "20260922_3rscan_semantic_c670", "20260922_3rscan_semantic_chairs",
        "20261001_3rscan_pair06", "20261001_3rscan_pair07", "20261001_3rscan_pair08",
    }
    for run_name in expected_native_runs:
        run_config = json.loads((root / "outputs/runs" / run_name / "config.json").read_text(encoding="utf-8"))
        require(run_config.get("coordinate_convention") == "native_scan_frames", f"{run_name} coordinate convention drifted")

    result = {
        "status": "pass",
        "source_pairs": int(len(source)),
        "vitg_source_weighted_coverage": weighted_coverage,
        "vitg_source_weighted_semantic": weighted_semantic,
        "vitg_source_strict_pose_successes": int(pose_success),
        "fpfh_one_way_weighted_coverage": fpfh_coverage,
        "fpfh_one_way_weighted_semantic": fpfh_semantic,
        "fpfh_one_way_strict_pose_successes": int(fpfh_pose),
        "fcgf_top20_weighted_coverage": fcgf_coverage,
        "fcgf_top20_weighted_semantic": fcgf_semantic,
        "fcgf_top20_strict_pose_successes": int(fcgf_pose),
        "negative_control_weighted_coverage": negative_coverage,
        "negative_control_weighted_semantic": negative_semantic,
        "negative_control_strict_pose_successes": int(negative_pose),
        "negative_control_target_coverage": float(negative_target.inlier_coverage),
        "negative_control_target_semantic": float(negative_target.inlier_semantic_accuracy),
        "calibrated_threshold_m": float(-fit.threshold),
        "target_calibrated_semantic_mIoU": float(target_transfer.semantic_mIoU),
        "target_calibrated_instance_mIoU": float(target_transfer.instance_mIoU),
        "annotation_projection_samples": int(projection_audit["samples"]),
        "annotation_projection_nonzero_label_rate": float(projection_audit["nonzero_label_rate"]),
    }
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
